name: shewa_ui_kit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - packages/shewa_ui_kit/assets/countries/countries.json
    - packages/shewa_ui_kit/assets/countries/flags/ad.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ae.jpg
    - packages/shewa_ui_kit/assets/countries/flags/af.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ag.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ai.jpg
    - packages/shewa_ui_kit/assets/countries/flags/al.jpg
    - packages/shewa_ui_kit/assets/countries/flags/am.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ao.jpg
    - packages/shewa_ui_kit/assets/countries/flags/aq.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ar.jpg
    - packages/shewa_ui_kit/assets/countries/flags/as.jpg
    - packages/shewa_ui_kit/assets/countries/flags/at.jpg
    - packages/shewa_ui_kit/assets/countries/flags/au.jpg
    - packages/shewa_ui_kit/assets/countries/flags/aw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ax.jpg
    - packages/shewa_ui_kit/assets/countries/flags/az.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ba.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bb.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bd.jpg
    - packages/shewa_ui_kit/assets/countries/flags/be.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bh.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bi.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bj.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bo.jpg
    - packages/shewa_ui_kit/assets/countries/flags/br.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bs.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/by.jpg
    - packages/shewa_ui_kit/assets/countries/flags/bz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ca.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cd.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ch.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ci.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ck.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/co.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cv.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cx.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cy.jpg
    - packages/shewa_ui_kit/assets/countries/flags/cz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/de.jpg
    - packages/shewa_ui_kit/assets/countries/flags/dj.jpg
    - packages/shewa_ui_kit/assets/countries/flags/dk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/dm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/do.jpg
    - packages/shewa_ui_kit/assets/countries/flags/dz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ec.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ee.jpg
    - packages/shewa_ui_kit/assets/countries/flags/eg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/er.jpg
    - packages/shewa_ui_kit/assets/countries/flags/es.jpg
    - packages/shewa_ui_kit/assets/countries/flags/et.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fi.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fj.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fo.jpg
    - packages/shewa_ui_kit/assets/countries/flags/fr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ga.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gb.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gd.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ge.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gh.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gi.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gp.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gq.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gs.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/gy.jpg
    - packages/shewa_ui_kit/assets/countries/flags/hk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/hn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/hr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ht.jpg
    - packages/shewa_ui_kit/assets/countries/flags/hu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/id.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ie.jpg
    - packages/shewa_ui_kit/assets/countries/flags/im.jpg
    - packages/shewa_ui_kit/assets/countries/flags/in.jpg
    - packages/shewa_ui_kit/assets/countries/flags/io.jpg
    - packages/shewa_ui_kit/assets/countries/flags/iq.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ir.jpg
    - packages/shewa_ui_kit/assets/countries/flags/is.jpg
    - packages/shewa_ui_kit/assets/countries/flags/it.jpg
    - packages/shewa_ui_kit/assets/countries/flags/je.jpg
    - packages/shewa_ui_kit/assets/countries/flags/jm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/jo.jpg
    - packages/shewa_ui_kit/assets/countries/flags/jp.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ke.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kh.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ki.jpg
    - packages/shewa_ui_kit/assets/countries/flags/km.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kp.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ky.jpg
    - packages/shewa_ui_kit/assets/countries/flags/kz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/la.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lb.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/li.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ls.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/lv.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ly.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ma.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/md.jpg
    - packages/shewa_ui_kit/assets/countries/flags/me.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mh.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ml.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mo.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mp.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mq.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ms.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mv.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mx.jpg
    - packages/shewa_ui_kit/assets/countries/flags/my.jpg
    - packages/shewa_ui_kit/assets/countries/flags/mz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/na.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ne.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ng.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ni.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/no.jpg
    - packages/shewa_ui_kit/assets/countries/flags/np.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/nz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/om.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pa.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pe.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ph.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ps.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/pw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/py.jpg
    - packages/shewa_ui_kit/assets/countries/flags/qa.jpg
    - packages/shewa_ui_kit/assets/countries/flags/re.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ro.jpg
    - packages/shewa_ui_kit/assets/countries/flags/rs.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ru.jpg
    - packages/shewa_ui_kit/assets/countries/flags/rw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sa.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sb.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sd.jpg
    - packages/shewa_ui_kit/assets/countries/flags/se.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sh.jpg
    - packages/shewa_ui_kit/assets/countries/flags/si.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sj.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/so.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ss.jpg
    - packages/shewa_ui_kit/assets/countries/flags/st.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sv.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sx.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sy.jpg
    - packages/shewa_ui_kit/assets/countries/flags/sz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/td.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/th.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tj.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tl.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/to.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tr.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tv.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tw.jpg
    - packages/shewa_ui_kit/assets/countries/flags/tz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ua.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ug.jpg
    - packages/shewa_ui_kit/assets/countries/flags/us.jpg
    - packages/shewa_ui_kit/assets/countries/flags/uy.jpg
    - packages/shewa_ui_kit/assets/countries/flags/uz.jpg
    - packages/shewa_ui_kit/assets/countries/flags/va.jpg
    - packages/shewa_ui_kit/assets/countries/flags/vc.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ve.jpg
    - packages/shewa_ui_kit/assets/countries/flags/vg.jpg
    - packages/shewa_ui_kit/assets/countries/flags/vi.jpg
    - packages/shewa_ui_kit/assets/countries/flags/vn.jpg
    - packages/shewa_ui_kit/assets/countries/flags/vu.jpg
    - packages/shewa_ui_kit/assets/countries/flags/wf.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ws.jpg
    - packages/shewa_ui_kit/assets/countries/flags/xk.jpg
    - packages/shewa_ui_kit/assets/countries/flags/ye.jpg
    - packages/shewa_ui_kit/assets/countries/flags/yt.jpg
    - packages/shewa_ui_kit/assets/countries/flags/za.jpg
    - packages/shewa_ui_kit/assets/countries/flags/zm.jpg
    - packages/shewa_ui_kit/assets/countries/flags/zw.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
